### ISSUE TITLE
iOS networkActivityIndicator

### ISSUE THREAD

**Issue by orangefour** [Cutehacks/duperagent#7]
Have you considered adding 

    [UIApplication sharedApplication].networkActivityIndicatorVisible = YES;

I need such a thing. I would appreciate your opinion whether this is easily doable and some hints on how to implement it

**Comment by jrbarron** [comment]
Hi @orangefour, I haven't done much iOS development myself so I was not aware that this flag existed. If I understand it correctly, the flag should be set to `YES` when there are pending network requests and then subsequently set back to false when all have finished. Is that correct?

This could probably be solved in Duperagent by maintaining a count of pending network requests (or alternatively a list). It probably makes sense to expose a flag so this behavior is configurable from QML.

You might be able to solve this yourself for now by adding event listeners to Duperagent using the `on` function. The 2 events you are interested in would be `request` and `end`. You could use those events to maintain your own counter and then add code to call the above iOS function. I'll leave the task open though since it does sound like a useful feature to add.

**Comment by jrbarron** [comment]
AFNetworking seems to expose a nice API for this: http://cocoadocs.org/docsets/AFNetworking/3.1.0/Classes/AFNetworkActivityIndicatorManager.html

**Comment by orangefour** [comment]
Yes, the flag should be set to `NO` in the end. And `AFNetworking` looks like the easier way to go since it handles the counter and adds some nice features like delay. Unfortunately it is does not come with XCode and has to be installed separately

**Comment by jrbarron** [comment]
@orangefour I wouldn't pull in AFNetworking as a dependency, I would just use their API for inspiration. The settings that control the delay are quite nice IMO ;)
